# Print the base API URL after Terraform deploys the stack.
output "api_endpoint" {
  # Describe what this output means.
  description = "Base HTTPS URL for the Lambda Function URL API."
  # Return the Function URL generated by AWS.
  value = aws_lambda_function_url.hello_url.function_url
}

# Print the GET test command after deployment.
output "get_test_command" {
  # Describe what this output means.
  description = "Curl command to test GET."
  # Build a copy-and-paste curl command for GET.
  value = "curl ${aws_lambda_function_url.hello_url.function_url}hello"
}

# Print the POST test command after deployment.
output "post_test_command" {
  # Describe what this output means.
  description = "Curl command to test POST with a JSON name argument."
  # Build a copy-and-paste curl command for POST.
  value = "curl -X POST ${aws_lambda_function_url.hello_url.function_url}hello -H 'Content-Type: application/json' -d '{\"name\":\"Zach\"}'"
}

# Print the Lambda function name for logs and troubleshooting.
output "lambda_function_name" {
  # Describe what this output means.
  description = "Name of the Lambda function created by Terraform."
  # Return the Lambda function name.
  value = aws_lambda_function.hello.function_name
}

# Print the CloudWatch log group name for troubleshooting.
output "lambda_log_group" {
  # Describe what this output means.
  description = "CloudWatch Log Group where Lambda writes logs."
  # Return the CloudWatch Log Group name.
  value = aws_cloudwatch_log_group.lambda_logs.name
}
